### PR TITLE
add new Mascot

### PR DESCRIPTION
**Pull request by RubenKelevra**
The logo referenced is published under CC-BY-SA 3.0, the Author is Jeyawue.

Preview:

Screenshot_20210414-104246

### CODE REVIEW

**Comment by RubenKelevra** [comment]
@Stebalien can you please add `bafykbzacebddch6dpmgdyupxygcbi2pvmzwiz7edmvwbtskseldpu3ofj5xjy` to the ipfs-website cluster if this PR gets accepted? 🤔

**Review by Stebalien — APPROVED** [review]
This is awesome.

**Comment by Stebalien** [comment]
Thanks!

**Comment by RubenKelevra** [comment]
@Stebalien wrote:
> This is awesome.

You're welcome. If you need some artwork for something lmk, she's a good friend of mine :)

**Comment by daviddias** [comment]
This is beautiful!!! amazing work! Thank you so much for updating this logo!!

**Pull request merged**
