### PR TITLE
refactor: drop DHT v1 compatibility

### PR DESCRIPTION
**Pull request by alanshaw**
Hydra deployment for go-ipfs 0.5.

### CODE REVIEW

**Comment by aschmahmann** [comment]
@alanshaw LGTM. @Stebalien I'm not sure what the intended timing of deployment for this is, do you mind coordinating with @alanshaw?

**Comment by alanshaw** [comment]
I was planning on merging, releasing and deploying this tomorrow. If you have a specific time in mind please say 😁

**Comment by Stebalien** [comment]
We need to sync up and deploy at the same time. Given timezones, that's a bit tricky. Can you meet at 18UTC? That way we can get infra on board at the same time?

Also, infra and/or someone else _NEEDS_ the ability to revert at a moments notice.

**Comment by alanshaw** [comment]
I can do 18:30 UTC. I'll update this PR to make the value configurable by environment var so we don't have to downgrade or switch to a different branch to back out.

**Pull request merged**
